#include "ExTimer.h"
/*
The 'clock()' function is defined in the 'ctime.h' header file.The clock() function returns the approximate processor time that is consumed by the whole program(not only the function where it's defined) with the unit of millisecond.
The clock() time depends upon how the operating system allocate resources to the process that¡¯s why clock() time may be slower or faster than the actual clock.
*/

//define a timer(which should be used in a loop) to control the moving speed of the ball:
int timer(int duration, int id)
{
    static int begin[10]; //the 'begin_time' is '0' ms
    int end = clock(); // the 'end_time' is generated by calling 'clock()'(defined in time.h).
    if (end - begin[id] >= duration) {
        //if the processing time of program passed the preset 'duration', update the begin_time and returns 'true'.
        begin[id] = end;
        return 1;
    }
    return 0;
}
